### ISSUE TITLE
Some of the links are underlined, others are not

### ISSUE THREAD

**Issue by ulrikah** [live-interfaces/liveinterfaces2020#1]
Where is the CSS style that defines the style?

**Comment by Oeyvind** [comment]
It is a Jekyll theme, with settings in the file _config.yml

As far as I understand Jekyll, the site is then autogenerated, looks lie it
is in the _site folder.
There is a css file in _site/assets/styles.css, but I don't think it makes
sense to edit is, as it will be overwritten when the site is updated
(happens soon-ish after you push changes to git).
I am no expert on this, so if some of what I say seems wrong, it might very
well be... please discuss :-)

ons. 18. sep. 2019 kl. 15:20 skrev ulrikah <notifications@github.com>:
