### ISSUE TITLE
Why is /liveinterfaces2020 the base URL?

### ISSUE THREAD

**Issue by ulrikah** [live-interfaces/liveinterfaces2020#2]
Is there any particular reason why the base URL is not simply _https//live-interfaces.github.io/_ instead of _https//live-interfaces.github.io/liveinterfaces2020_ ?

**Comment by Oeyvind** [comment]
Hei Ulrik.

Det er fordi live-interfaces er registrert som en organisasjon på github,
og liveinterfaces2020 et et prosjekt under denne organisasjonen. Vi vil
gjerne samle alle websider for konferansen på ett sted. Websidene for 2018
er også lagt inn på live-interfaces/2018. Tidligere år skal etterhvert også
ligge likedan.
Har du en god måte for forwarding? Akkurat nå har jeg lagt inn en meta tag
med refresh. Det funker men er visstnok en stygg måte å gjøre det på.

tor. 26. sep. 2019, 12:09 p.m. skrev ulrikah <notifications@github.com>:

**Comment by Oeyvind** [comment]
Jeg skriver dette fra telefonen, for jeg er på reise. Kanskje vi skal
treffes en dag til uka? Det er nok mange detaljer som er lettere å snakke
om enn å skrive.

tor. 26. sep. 2019, 2:29 p.m. skrev Oeyvind Brandtsegg <obrandts@gmail.com>:
